version: 2.1

jobs:
  console:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: cp .env.sample .env && make verify
  tag:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: sh scripts/tag.sh
  publish-console:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: sh scripts/publish-console.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - console
      - tag:
          requires:
            - console
          filters:
            branches:
              only: master
      - publish-console:
          requires:
            - tag
          filters:
            branches:
              only: master
